In [3]:
import pandas as pd 
import matplotlib.pyplot as plt
import random
from sklearn import preprocessing
import sklearn as skl
import numpy as np

In [4]:
data = pd.read_csv("churn.csv", header=None, sep=';') 
# Preview the first 5 lines of the loaded data 
data.head()
 
# 197443 - test


train_data = pd.DataFrame(preprocessing.normalize(data.iloc[:,1:]))
train_data.head()

,0,1,2,3,4,5,6,7,8,9,...,24,25,26,27,28,29,30,31,32,33
0,0.0,0.0,0.0,0.068120,0.170301,0.170301,0.170301,0.170301,0.306541,0.170301,...,0.034060,0.102180,0.170301,0.510902,0.374661,0.238421,0.068120,0.170301,0.238421,0.102180
1,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.013789,0.358527,0.165474,0.275790,...,0.151684,0.096526,0.041368,0.248211,0.399895,0.206842,0.317158,0.068947,0.000000,0.000000
2,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.141421,0.070711,0.070711,0.212132,0.141421,0.000000,0.000000,0.000000,0.000000
3,0.0,0.0,0.0,0.000000,0.322562,0.107521,0.107521,0.000000,0.215041,0.215041,...,0.053760,0.107521,0.053760,0.053760,0.053760,0.107521,0.000000,0.000000,0.000000,0.161281
4,0.0,0.0,0.0,0.024915,0.124573,0.149487,0.099658,0.124573,0.049829,0.000000,...,0.174402,0.224231,0.074744,0.249145,0.448461,0.274060,0.298974,0.174402,0.249145,0.099658

In [21]:
reverse_df = pd.DataFrame(train_data.iloc[:, ::-1])

In [39]:
reverse_df.columns[::-1]

RangeIndex(start=0, stop=34, step=1)

In [355]:
pd.set_option('display.max_columns', 500)

train_data.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33
0,0.0,0.0,0.0,0.068120,0.170301,0.170301,0.170301,0.170301,0.306541,0.170301,0.272481,0.068120,0.102180,0.034060,0.034060,0.136241,0.068120,0.034060,0.034060,0.068120,0.102180,0.068120,0.136241,0.034060,0.034060,0.102180,0.170301,0.510902,0.374661,0.238421,0.068120,0.170301,0.238421,0.102180
1,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.013789,0.358527,0.165474,0.275790,0.137895,0.303369,0.110316,0.220632,0.193053,0.179263,0.137895,0.151684,0.262000,0.000000,0.000000,0.000000,0.110316,0.000000,0.151684,0.096526,0.041368,0.248211,0.399895,0.206842,0.317158,0.068947,0.000000,0.000000
2,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.424264,0.494975,0.565685,0.282843,0.141421,0.070711,0.070711,0.070711,0.000000,0.212132,0.000000,0.000000,0.141421,0.070711,0.070711,0.212132,0.141421,0.000000,0.000000,0.000000,0.000000
3,0.0,0.0,0.0,0.000000,0.322562,0.107521,0.107521,0.000000,0.215041,0.215041,0.215041,0.107521,0.430083,0.053760,0.107521,0.268802,0.215041,0.322562,0.268802,0.322562,0.053760,0.107521,0.215041,0.053760,0.053760,0.107521,0.053760,0.053760,0.053760,0.107521,0.000000,0.000000,0.000000,0.161281
4,0.0,0.0,0.0,0.024915,0.124573,0.149487,0.099658,0.124573,0.049829,0.000000,0.024915,0.149487,0.024915,0.124573,0.174402,0.298974,0.249145,0.174402,0.099658,0.074744,0.099658,0.124573,0.049829,0.149487,0.174402,0.224231,0.074744,0.249145,0.448461,0.274060,0.298974,0.174402,0.249145,0.099658

In [394]:
timestamp = 3 
prepering_data_x = pd.DataFrame()

for index, row in reverse_df.iterrows():
    
    close_event_col = -.5
    if(index == 3):   
        for i in (range(0, len(row)-timestamp+1)):
            s = pd.Series([index])
            s = s.append(row[i:i+timestamp])
            if(row[i:i+timestamp] > 0):
                print(1)
            if(row[i:i+timestamp].values[timestamp-1] > 0):
                close_event_col = i
                s = s.append(pd.Series([0.5]))
                


            else:
                col_ = i - close_event_col + 0.5
                s = s.append(pd.Series([col_]))

            prepering_data_x = prepering_data_x.append([s.values], ignore_index=False)
    if(index == 10):        
        break

prepering_data_x

ValueError: can only convert an array of size 1 to a Python scalar

In [350]:
prepering_data

     0         1         2         3    4
0  0.0  0.102180  0.238421  0.170301  0.5
0  0.0  0.238421  0.170301  0.068120  0.5
0  0.0  0.170301  0.068120  0.238421  0.5
0  0.0  0.068120  0.238421  0.374661  0.5
0  0.0  0.238421  0.374661  0.510902  0.5
0  0.0  0.374661  0.510902  0.170301  0.5
0  0.0  0.510902  0.170301  0.102180  0.5
0  0.0  0.170301  0.102180  0.034060  0.5
0  0.0  0.102180  0.034060  0.034060  0.5
0  0.0  0.034060  0.034060  0.136241  0.5
0  0.0  0.034060  0.136241  0.068120  0.5
0  0.0  0.136241  0.068120  0.102180  0.5
0  0.0  0.068120  0.102180  0.068120  0.5
0  0.0  0.102180  0.068120  0.034060  0.5
0  0.0  0.068120  0.034060  0.034060  0.5
0  0.0  0.034060  0.034060  0.068120  0.5
0  0.0  0.034060  0.068120  0.136241  0.5
0  0.0  0.068120  0.136241  0.034060  0.5
0  0.0  0.136241  0.034060  0.034060  0.5
0  0.0  0.034060  0.034060  0.102180  0.5
0  0.0  0.034060  0.102180  0.068120  0.5
0  0.0  0.102180  0.068120  0.272481  0.5
0  0.0  0.068120  0.272481  0.170301  0.5
0  0.0  0.272481  0.170301  0.306541  0.5
0  0.0  0.170301  0.306541  0.170301  0.5
0  0.0  0.306541  0.170301  0.170301  0.5
0  0.0  0.170301  0.170301  0.170301  0.5
0  0.0  0.170301  0.170301  0.170301  0.5
0  0.0  0.170301  0.170301  0.068120  0.5
0  0.0  0.170301  0.068120  0.000000  1.5
0  0.0  0.068120  0.000000  0.000000  2.5
0  0.0  0.000000  0.000000  0.000000  3.5

In [6]:
export_csv = (train_data.head()).to_csv (r'export_dataframe.csv', index = None, header=False) #Don't forget to add '.csv' at the end of the path